// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYBkCk5W_aefrP1U9ZgJHxMqIABiYd9Zg',
    appId: '1:304864330729:web:698288d76e2a39ca564178',
    messagingSenderId: '304864330729',
    projectId: 'impossiblealwaysontrack',
    authDomain: 'impossiblealwaysontrack.firebaseapp.com',
    storageBucket: 'impossiblealwaysontrack.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRyW46EgKVZ0TSY2lS_L4YVWUORE9PhM4',
    appId: '1:304864330729:android:4dbfb3caba6be415564178',
    messagingSenderId: '304864330729',
    projectId: 'impossiblealwaysontrack',
    storageBucket: 'impossiblealwaysontrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjYjAne1vye7okVm_COpA9Gk-S4HjAtGI',
    appId: '1:304864330729:ios:0e340faddc20a2a3564178',
    messagingSenderId: '304864330729',
    projectId: 'impossiblealwaysontrack',
    storageBucket: 'impossiblealwaysontrack.firebasestorage.app',
    iosBundleId: 'com.example.alwaysontrackimpossible',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjYjAne1vye7okVm_COpA9Gk-S4HjAtGI',
    appId: '1:304864330729:ios:0e340faddc20a2a3564178',
    messagingSenderId: '304864330729',
    projectId: 'impossiblealwaysontrack',
    storageBucket: 'impossiblealwaysontrack.firebasestorage.app',
    iosBundleId: 'com.example.alwaysontrackimpossible',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYBkCk5W_aefrP1U9ZgJHxMqIABiYd9Zg',
    appId: '1:304864330729:web:9b17c58b090a2f87564178',
    messagingSenderId: '304864330729',
    projectId: 'impossiblealwaysontrack',
    authDomain: 'impossiblealwaysontrack.firebaseapp.com',
    storageBucket: 'impossiblealwaysontrack.firebasestorage.app',
  );
}
